export default {
  COLORS: {
    DEFAULT: '#172B4D',
    PRIMARY: '#5E72E4',
    SECONDARY: '#F7FAFC',
    LABEL: '#FE2472',
    INFO: '#11CDEF',
    ERROR: '#F5365C',
    SUCCESS: '#2DCE89',
    WARNING: '#FB6340',
    WHITE: '#FFFFFF',
    BLACK: '#000000',
    PLANTE: "",
    FEU:"",
    EAU:"",
    ACIER:"",
    COMBAT:"",
    DRAGON:"",
    ELECTRIK:"",
    FEE:"",
    GLACE:"",
    INSECTE:"",
    NORMAL:"",
    POISON:"",
    PSY:"",
    ROCHER:"",
    SOL:"",
    SPECTRE:"",
    TENEBRE:"",
    VOL:"",
  },
};
